"""
init for the exceptions module
"""
from .exceptions import ProtocolError
